### ISSUE TITLE
Subscription restoring

### ISSUE THREAD

**Issue by SebaDro** [52North/sensor-things#8]
If subscription persistence is enabled a `NullPointerException` occurs when trying to validate the topic pattern for the subscription:
```
Caused by: java.lang.NullPointerException: null
	at org.n52.sta.utils.UriResourceNavigationResolver.resolveSimpleEntityRequest(UriResourceNavigationResolver.java:173)
	at org.n52.sta.mqtt.handler.MqttEntitySubscriptionHandler.createResponseForEntity(MqttEntitySubscriptionHandler.java:51)
	at org.n52.sta.mqtt.handler.MqttEntitySubscriptionHandler.handleEntityRequest(MqttEntitySubscriptionHandler.java:40)
	at org.n52.sta.mqtt.handler.MqttEntitySubscriptionHandler.handleEntityRequest(MqttEntitySubscriptionHandler.java:27)
	at org.n52.sta.mqtt.handler.MqttMessageHandler.validateResource(MqttMessageHandler.java:131)
	at org.n52.sta.mqtt.handler.MqttMessageHandler.validateTopicPattern(MqttMessageHandler.java:102)
	at org.n52.sta.mqtt.handler.MqttMessageHandler.createMqttSubscription(MqttMessageHandler.java:90)
	at org.n52.sta.mqtt.handler.MqttMessageHandler.processSubscribeMessage(MqttMessageHandler.java:82)
	at org.n52.sta.mqtt.core.MqttBroker.restoreSubscriptions(MqttBroker.java:118)
	at org.n52.sta.mqtt.core.MqttBroker.initMQTTBroker(MqttBroker.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 58 common frames omitted
```
Since [`public Server initMQTTBroker()`](https://github.com/52North/sensor-things/blob/5a9b976ed15b86918b7d97d98bda6ef6f014737a/sensor-things-api-mqtt/src/main/java/org/n52/sta/mqtt/core/MqttBroker.java#L91-L106) within `MqttBroker` is Spring configured, it will be called before [`public void init()`](https://github.com/52North/sensor-things/blob/26d7e0ea4cb384f780cd08550324fa714bcb94a7/sensor-things-api-core/src/main/java/org/n52/sta/data/service/AbstractSensorThingsEntityService.java#L69-L72) from `AbstractSensorThingsEntityService`.  As a result, [`EntityServiceRepository`](https://github.com/52North/sensor-things/blob/5a9b976ed15b86918b7d97d98bda6ef6f014737a/sensor-things-api-core/src/main/java/org/n52/sta/data/service/EntityServiceRepository.java#L29) has no registered services and so an empty _Map_ of `AbstractSensorThingsEntityService`.  So when `UriResourceNavigationResolver` comes to call [`resolveSimpleEntityRequest`](https://github.com/52North/sensor-things/blob/5a9b976ed15b86918b7d97d98bda6ef6f014737a/sensor-things-api-core/src/main/java/org/n52/sta/utils/UriResourceNavigationResolver.java#L169) it receives `null` for the requested `AbstractSensorThingsEntityService`.  
https://github.com/52North/sensor-things/blob/5a9b976ed15b86918b7d97d98bda6ef6f014737a/sensor-things-api-core/src/main/java/org/n52/sta/utils/UriResourceNavigationResolver.java#L172-L173)

**Comment by SebaDro** [comment]
In addition, it should be evaluated if the topic validation has to be applied when initializing the broker. Since topics will be validated when clients subscribe for it, such a validation at initialization would be redundant because stored subscriptions are valid subscriptions. It would be a better approach to store those parameters, that allow restoring subscriptions without a need for validating topics.

**Comment by SpeckiJ** [comment]
> it should be evaluated if the topic validation has to be applied when initializing the broker

As the Datasource might have changed in the meantime (e.g. wipe of the database, switch of the datasource during the downtime, manual editing of datasource, editing of datasource by other programs working on the same datasource, etc.) this validation is strictly necessary. (Additionally, the validation only needs to be done once upon startup, and the performance benefit from skipping the validation is minimal.)

https://github.com/52North/sensor-things/commit/b550bc36684f64fa0a6c0c5c49f476efdeeff00f should fix the issue by restoring the Subscriptions only after the whole Infrastructure has been set up.
